### ISSUE TITLE
Extend xSPWebApplication resource to include "Site Use Confirmation and Deletion" settings

### ISSUE THREAD

**Issue by ykuijs** [PowerShell/xSharePoint#112]
Extend the xSPWebAppliation resource top include the follow settings (seen in central admin under the "Application Management > Site Collections > Confirm site use and deletion" menu, http://<central_admin_url>/_admin/DeleteSiteConfig.aspx)
* Configure SharePoint to send out site usage confirmation e-mails to owners
* Configure SharePoint to delete sites when not confirmed after x notices

**Comment by BrianFarnhill** [comment]
@ykuijs You wanna work on this one, or just adding to the list of enhancements? Happy for either, just wanted to know if I need to leave it as help wanted or not

**Comment by ykuijs** [comment]
@BrianFarnhill - I am on it!

**Comment by BrianFarnhill** [comment]
All yours @ykuijs

**Comment by ykuijs** [comment]
@BrianFarnhill - I think this issue can be close, since the resource was created already
