### ISSUE TITLE
Idea: Everything as a module

### ISSUE THREAD

**Issue by camiloborges** [PowerShell/xSharePoint#127]
hey, just putting it out there...
what if all resources were available as modules, similarly to the xSPWebApplication ones? 

Then everyone could use xSharePoint in the 'classic' way

**Comment by BrianFarnhill** [comment]
To be fair the only reason I left the web app ones that way was because I can see us merging them back in to the complex types approach we went for at first (post the issues being resolved). I don't think there is much of a need to call them directly (outside of a configuration per se), the goal of the project was to facilitate the use of DSC for SharePoint. What are you hoping to gain out of that approach?

**Comment by camiloborges** [comment]
few reasons, but mainly #1
1) It is a lot easier to do integration test as a module
2) allow 'classic' admin to use IP as an ad-hoc call
3) adoption. many people have no clue what DSC is, and might not try
xSharePoint because of that.

It all started with the time it took me to troublesthoot the issues I was
having with the UPS Sync Connection. I don't know If I just don't know
something, but I just don't know how to debug the code in the DSC resource
:)

**Comment by BrianFarnhill** [comment]
ok, so some follow up questions:

1 - how is it easier to integration test? My process normally involves me doing this:

    Import-Module C:\Program Files\WindowsPowerShell\modules\xSharePoint\DSCREsources\RESOURCENAME\RESOURCENAME.psm1
    Get-TargetResource {params}

this way i can call a test and see it run - or you can even load that up in ISE and ddebug your way through things if you need to

2 and 3) I think allowing "classic" use of these as you put it is actually going to hurt adoption of these as proper DSC resources. I think if we are looking at adoption issues then we need to help educate on how they are meant to be used (a challenge I'm aware of already) as opposed to twisting what we are delivering to be used in a way that it wasn't designed for if that makes sense. 

So ultimately I think if we can get you debugging things a bit better we should be fine here - I'm thinking changing and adding another layer of modules to things will be a lot of extra script and nesting for not a lot of gain

**Comment by camiloborges** [comment]
all points taken :)
And thank you. This will make my life a lot easier :D
