### ISSUE TITLE
Resource description in MOF file xSPWebAppPolicy is incorrect

### ISSUE THREAD

**Issue by ykuijs** [PowerShell/xSharePoint#144]
The MOF file of the xSPWebAppPolicy resource (xSPWebAppPolicy.schema.mof) is incorrect. It is probably copied from the xSPCacheAccounts resource and never changed.

**Comment by BrianFarnhill** [comment]
Ahhh the documentation is in correct - leave it with me, will patch it up.

**Comment by ykuijs** [comment]
Working on implementing the changed resource. Have included this update as well. Will create a PR when done.

**Comment by BrianFarnhill** [comment]
This has been merged to dev, closing this issue
