### ISSUE TITLE
Extend xSPWebAppPolicy resource

### ISSUE THREAD

**Issue by ykuijs** [PowerShell/xSharePoint#147]
The current version of the xSPWebAppPolicy resource is only able to add new users. It is not able to remove users (Ensure=Absent) or enforce a specific list of users. See xSPFarmAdministrator group as an example.

Also: I haven't been able to test this yet, but reviewing the code I think the code does not handle claims users and classic users the correct way. The resource needs to be able to make a distinction between these two types of users. Using Central Admin you are only able to add claims users, but by using the SPWebApplication.GrantAccessToProcessIdentity method you can add classic identities. This is required in some cases, like using remote PowerShell to access specific properties (e.g. AllowDesigner) of the SPSite object.

**Comment by BrianFarnhill** [comment]
@ykuijs We did test the claims stuff in that it assumes if it can't find a match for the user through the basic string name then it tries to interpret it as a claims identity. So the theory is that if you specify it through the DSC you only user user the non-claims version of it and it'll get matched either way. If you test it and see that it does something different let me know though. Happy to agree to the other changes you opened with though

**Comment by ykuijs** [comment]
Am going to test this one and implement the changes suggested earlier.

**Comment by ykuijs** [comment]
@BrianFarnhill : Ok, have tested it. Here are the results:
As you specified, when the policy contains the claim value for the user and the resource specifies the domain\user format user, the resource returns true. This means that there is no way anymore (using DSC) you can add the domain\user format. However as specified in my first post, in some cases this is required to have SharePoint work properly.

I therefore would like to suggest to change this to match the string in the resource with the string in the policy. That way, you have to specify the claims value if you would like to add the claims value and the domain\user value if your want to add the domain\user value.

**Comment by ykuijs** [comment]
Working on this one

**Comment by ykuijs** [comment]
Also including #144

**Comment by BrianFarnhill** [comment]
@ykuijs Ping me to talk about this one again - I can't remember the spcifics of how we were approaching this and want to be sure we don't lose functionality. Thanks dude

**Comment by ykuijs** [comment]
Check your mail

**Comment by ykuijs** [comment]
New addition after a discussion with Brian:
Add SetCacheAccountsPolicy (boolean) property to make sure the Cache Accounts are also added (in claims format) to the policy.

**Comment by BrianFarnhill** [comment]
This has been merged to dev, closing this issue
