### ISSUE TITLE
$Ensure Parameter

### ISSUE THREAD

**Issue by camiloborges** [PowerShell/xSharePoint#148]
Hey.
I noticed some of the resources have the 'Ensure' parameter. Shouldn't all of them have it?

**Comment by BrianFarnhill** [comment]
Pretty much yes - feel free to call it out in the comments on any outstanding issues that don't have it, and we can raise issues for ones that are missing it.

**Comment by camiloborges** [comment]
Cool. deal

**Comment by ykuijs** [comment]
I would suggest only to include them when it makes sense. For example
- The xSPFarmAdministrators resource doesn't need to have the ensure parameter, since the currently specified parameters are (imho) sufficient.
- A Service Application resource requires one, since you need to be able to specify it the SA needs to be present or not.

**Comment by camiloborges** [comment]
agree with @ykuijs , not all need it, but many do. I went through the list we have in the latest release and documented them.

resources with missing Ensure
MSFT_xSPWebAppPolicy: Ensure would remove given user from web app policies
MSFT_xSPWebApplication 
MSFT_xSPVisioServiceApp
MSFT_xSPUsageApplication
MSFT_xSPSubscriptionSettingsServiceApp
MSFT_xSPStateServiceApp
MSFT_xSPSite
MSFT_xSPSessionStateService
MSFT_xSPServiceAppPool
MSFT_xSPSecureStoreServiceApp
MSFT_xSPSearchServiceApp
MSFT_xSPManagedPath
MSFT_xSPManagedMetadataServiceApp
MSFT_xSPManagedAccount
MSFT_xSPBCSServiceApp
MSFT_xSPAppManagementServiceApp

**Comment by BrianFarnhill** [comment]
Pretty happy with this list - I'll put this in to the enhancement category and we can capture this in a future udpate.

**Comment by camiloborges** [comment]
Hey, I think we need to address this for V1.0. It believe we'll also benefit from having it when we get the reverse module sorted out

**Comment by BrianFarnhill** [comment]
I'm taking this one to get it in for 1.0

**Comment by BrianFarnhill** [comment]
Merged in to dev, closing this issue
