### ISSUE TITLE
Add xSPShellAdmins resource

### ISSUE THREAD

**Issue by ykuijs** [PowerShell/xSharePoint#149]
The xSPShellAdmins resource will be used to manage the accounts that have Shell Admin permissions. It will be represented as below:

xSPShellAdmins ShellAdmins
{
 Members=”DOMAIN\UserX”, "BUILTIN\Administrators", "DOMAIN\sp_farm"
 MembersToInclude=""DOMAIN\User1"
 MembersToExclude="DOMAIN\User2"
 AllContentDatabases=$true
}

The Members property is used to enforce a specific list of users which have to be a member of the Farm Administrators group and cannot be used together with the MembersToInclude and/or MembersToExclude properties.
 The MembersToInclude and MembersToExclude properties are used to make sure one (or a set of) user is added to Farm Admins (MembersToInclude) or a user can never be a member of the Farm Admins (MembersToExclude).

This resource is similar to the xSPFarmAdministrators resource.

**Comment by ykuijs** [comment]
Working on it!

**Comment by BrianFarnhill** [comment]
Added to v0.10 - closing this issue
