### ISSUE TITLE
When published to the Gallery the Tags property doesnt include that this has DSC Resources

### ISSUE THREAD

**Issue by kilasuit** [PowerShell/xSharePoint#153]
Please on the next Update add the DSCResource to the Tags along with other required updates.

**Comment by BrianFarnhill** [comment]
@KarolKaczmarek Can you comment on this one please?

**Comment by kilasuit** [comment]
Also as a further FYI the LicenseURI & ProjectURI doesn't push through to the gallery - when not put in the PSD1 file see this UserVoice Issue regarding this http://windowsserver.uservoice.com/forums/301869-powershell/suggestions/11439807-gallery-issue-licenseuri-projecturi-aren-t-add

**Comment by KarolKaczmarek** [comment]
Thanks for headsup @kilasuit 

Previously published version had license, project and tags populated correctly (http://www.powershellgallery.com/packages/xSharePoint/0.7.0.0 ), so it looks like there's some regression with Publish-Module cmdlet we use in our automation to publish modules.  

I've already followed up with the PowerShell Gallery team about it. 
Will keep you updated.



Thanks,
Karol

**Comment by kilasuit** [comment]
@KarolKaczmarek Could you please point them to this blog post http://bit.ly/PSGalleryAutoBot1 on the issues that I've seen with the PowerShell Gallery (I run an Autobot on Twitter - @ThePSGalllery) and if needs be they can reach out directly to me on this via email ryan.yates@kilasuit.org

**Comment by kilasuit** [comment]
It seems that currently the psd1 file needs to contain the LicenseURI & ProjectURI for it to be discoverable in the PowerShell Gallery and I would recommend that this is updated in this & other Repo's as this info should be in there anyway - though thats just my opinion ;-p

**Comment by KarolKaczmarek** [comment]
@kilasuit Thanks, forwarded to the team.

**Comment by BrianFarnhill** [comment]
Seeing that his is bring tracked in the main DscResources repo, any objection to closing this issue off @kilasuit @KarolKaczmarek ?

**Comment by kilasuit** [comment]
Closed as per @BrianFarnhill suggestion above

Found that this isn't localised to the xSharePoint Module and is being tracked via main DSC Resource Repo
