### ISSUE TITLE
xSPSubscriptionSettingsServiceApp Proxy

### ISSUE THREAD

**Issue by NaomiReeves** [PowerShell/xSharePoint#163]
I'm working on configuring my app domain with DSC and Chef and had been receiving errors indicating that I need to configure my Subscription Settings. I discovered that even though I was using the Subscription Service resource, the Subscription Service Proxy hadn't been configured. Upon investigation of the module code it looks like it doesn't create the proxy. Is the intent to create a separate resource for the proxy? Based on [#24](https://github.com/PowerShell/xSharePoint/issues/24), I wasn't certain if this module was supposed to create it in addition to the service application.

**Comment by camiloborges** [comment]
Hello. 
You can get around it by replacing line 66 on the resource code

            $serviceApp = New-SPSubscriptionSettingsServiceApplication @newParams
            $proxy = New-SPSubscriptionSettingsServiceApplicationProxy -ServiceApplication $serviceApp 

I am testing the fix to it right now. hopefully we can include it in the next release

**Comment by NaomiReeves** [comment]
Fantastic, I was just testing a similar fix in my code. Thanks for the help and quick response.

**Comment by camiloborges** [comment]
you might also want to add -DefaultProxyGroup too

**Comment by BrianFarnhill** [comment]
I love it when you guys figure stuff out for me. @camiloborges I can put the fix in with a couple of other bugs I'll be patching tonight ahead of the v0.10 release branch, so I'll pick this one up.

**Comment by camiloborges** [comment]
Hello.
Change is already done. I just ended up screwing up and pushing it to the
wrong branch....

**Comment by BrianFarnhill** [comment]
This fix is now in the dev branch and will go out in v0.10 next week. Closing this issue off
