### ISSUE TITLE
MSFT_xSPWorkManagementServiceApp breaking xSharePoint configurations

### ISSUE THREAD

**Issue by magnustomte** [PowerShell/xSharePoint#171]
When executing a configuration with xSharePoint 0.10.0.0 or later the following error occurs:

> ImportCimAndScriptKeywordsFromModule : Cim deserializer threw an error when deserializing file C:\Program Files\WindowsPowerShell\Modules\xSharePoint\0.10.0.0\DSCResources\MSFT_xSPWorkManagementServiceApp\MSFT_xSPWorkManagementServiceApp.Schema.mof.
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\PSDesiredStateConfiguration\PSDesiredStateConfiguration.psm1:1972 char:50
+ ... dResource = ImportCimAndScriptKeywordsFromModule -Module $mod -Resour ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], PSInvalidOperationException
    + FullyQualifiedErrorId : System.Management.Automation.PSInvalidOperationException,ImportCimAndScriptKeywordsFromModule
 
> ImportCimAndScriptKeywordsFromModule : Syntax Error. Number value is not valid: .
 At line:30, char:19
 Buffer:
nt;
    [Write] System.^UInt32 
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\PSDesiredStateConfiguration\PSDesiredStateConfiguration.psm1:1972 char:50
+ ... dResource = ImportCimAndScriptKeywordsFromModule -Module $mod -Resour ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], CimException
    + FullyQualifiedErrorId : Microsoft.Management.Infrastructure.CimException,ImportCimAndScriptKeywordsFromModule

I suspect this is due to the MOF file being incorrect when using e.g. `[Write] System.UInt32 MinimumTimeBetweenEwsSyncSubscriptionSearches;` vs `[Write] UInt32 MinimumTimeBetweenEwsSyncSubscriptionSearches;`

Also suspect that the MOF class name should've been MSFT_**xSP**WorkManagementServiceApp

**Comment by camiloborges** [comment]
Hello @magnustomte  
I am looking into it right now, I should be able to share a fix in a couple of hours.
Cheers

**Comment by BrianFarnhill** [comment]
@camiloborges Ping me with the fix - we've been caught out on this a couple of times so I want to write some unit tests that compile the MOF schemas to make sure we catch this sort of thing before a release next time.

**Comment by camiloborges** [comment]
Sure thing. Will do :)

**Comment by camiloborges** [comment]
Hello. fix implemented.
https://github.com/camiloborges/xSharePoint/tree/xSPWorkManagementApp

There was few inconsistencies with the mof schema as well as a rookie mistake whereby DSC Configuration would do the job, but an exception would be thrown when service is absent.

**Comment by BrianFarnhill** [comment]
@camiloborges Can you flick me a PR with that file in it so I can merge it to dev?

**Comment by camiloborges** [comment]
Sure. Will do tonight. Will need a manual merge

**Comment by ykuijs** [comment]
Issue should be resolved with PR #177, correct? If so, this issue can be closed.
