### ISSUE TITLE
Removing Visual Studio Project files and switch to Visual Studio code

### ISSUE THREAD

**Issue by BrianFarnhill** [PowerShell/xSharePoint#172]
Hey guys,

I'm contemplating removing the Visual Studio Project files (*.sln, *.psproj) as they are only there to facilitate us all using Visual Studio as the editor when working on xSharePoint, and adding some files that will enable support for [Visual Studio Code](https://code.visualstudio.com/) instead (making use of the new [PowerShell support](https://blogs.msdn.microsoft.com/powershell/2015/11/16/announcing-powershell-language-support-for-visual-studio-code-and-more/) for VS code)- with the good part of that being that you can use VS code, or you can not - those files won't get in the way or need updating as we add more files to the project (right now you need to keep saving the project file in Visual Studio and commiting that, then dealing with merges and conflicts of those files). 

So the pros - less dealing with merges of the project files that we'll remove, and really letting people use whatever they want to edit things 

Cons - harder to use Visual Studio because there isn't a folder view in it like there is in Visual Studio code

Anyone have any major objections to that change?

 - B

**Comment by camiloborges** [comment]
Hey. I quite like the idea, however, many people are not yet using Visual Studio Code, wouldn't that become a road blocker ? I just don't want to lose the traction and have even fewer people contributing to this project.

**Comment by BrianFarnhill** [comment]
Well in theory you don't need to use VS code - you could use whatever you wanted. The VS Code inclusion makes a folder called .vscode which we put a file launch.json in there, this tells VS code how to run the project (which at this point I think would just call the unit tests). So if you aren't using VS code then this doesn't hurt anyone. But outside of that you could just use PowerShell ISE or anything else at all really, because we won't be using those project files anymore.

**Comment by camiloborges** [comment]
I kinda like project files, but yes, using visual studio actually causes me more problems than solutions. I always end up using ISE to finish and test files, and have lost changes because of a not to "do you want to reload your files"?
Go for it. if anyone wants they can have their own Visual studio project files

**Comment by BrianFarnhill** [comment]
Actually that's a good point - I might add the project files to the ignore file for the project to make sure they don't sneak their way back in so people can still use them themselves if they like while not committing them.

**Comment by BrianFarnhill** [comment]
The changes for this are in #173 - I'll leave this open for a bit in case anyone else has feedback before I force it in to dev

**Comment by kilasuit** [comment]
I'm undecided on this and (I think) for good reasons

- I mainly use ISE
- I'm starting to use VS for other projects
- I'm undecided on how useful VSCode is in PS world
- Does removal (or non-removal) make much difference in getting started with this?

Regards the last point the OfficeDevPnP PowerShell repo still has them included (I only use this as a reference as I'm about to start some work on that repo)  

So my personal suggestion would be to keep them until v1.0 stage and possibly remove then

**Comment by BrianFarnhill** [comment]
So i dont think removing it makes a problem - most scripters are used to using the ISE anyway. I've had more feedback about the fact that people have to install Visual Studio and the PowerShell extensions for it and that doing so is a pain in the butt, so if anything taking it out removes that ramp up requirement here.

I've also just had a bit of a play around with the ISE and I may even up using that myself as well. I put a [file explorer extension](https://gallery.technet.microsoft.com/Powershell-ISE-Explorer-bfc92307) in and it's actually working really great, so that may be the new home for this sort of stuff for me instead of VS code. Either way - no Visual Studio though.

**Comment by kilasuit** [comment]
@BrianFarnhill - Ok now that makes things clearer to me and it looks like @KarolKaczmarek has merged #173 so this issue could now be closed
