### ISSUE TITLE
Add support for Secure Sockets Layer to xSPWebApplication

### ISSUE THREAD

**Issue by NaomiReeves** [PowerShell/xSharePoint#179]
I'm currently trying to configure a new web application to run on 443 and need to be able to set the Secure Sockets Layer to true. It looks like this is an option in the [xSPWebApplicationAppDomain](https://github.com/PowerShell/xSharePoint/blob/dev/Modules/xSharePoint/DSCResources/MSFT_xSPWebApplicationAppDomain/MSFT_xSPWebApplicationAppDomain.psm1). I think this would be a pretty helpful optional parameter if it was included in this resource.

**Comment by BrianFarnhill** [comment]
Hey @NaomiReeves 

I was actually pretty sure we put this in, but from the looks of it we didn't! I'm working on a customer gig that is going to need this as well so expect me to get that built in very shortly for the next release.

**Comment by NaomiReeves** [comment]
Great, thanks @BrianFarnhill 

As an FYI, I'm working on getting my system set up so I can contribute beyond just submitting issues.

**Comment by camiloborges** [comment]
@BrianFArnhill
I am also under the impression we had it. Perhaps we lost it when we split up he designer, workflow and app domain resources?
It should be pretty straight forward to implement anyway.
Need to highlight in the doco that admin needs to have certificate configured afterwards. 

Camilo Borges
Sent via iPhone while out and about

**Comment by BrianFarnhill** [comment]
@camiloborges Thats what I was thinking - its just one flag on the cmdlet though so it'll be quicker to just add than for me to dig through the history to find it. Like I said I'll literally need this for a customer this week or next so I'll get it back in.

**Comment by BrianFarnhill** [comment]
Told you I was gonna come across this one this week :P The fix is in #183 and will be in dev shortly!

**Comment by NaomiReeves** [comment]
Yea! Thanks so much, looks good.

**Comment by BrianFarnhill** [comment]
This just got merged to dev - closing this issue
