### ISSUE TITLE
No install bits in the examples?

### ISSUE THREAD

**Issue by tonyhxh** [PowerShell/xSharePoint#185]
There is no install bits in the examples?

Thanks
Tony H

**Comment by BrianFarnhill** [comment]
Thanks for letting us know Tony. I'll get them added in for the next release. In the mean time you can check out the wiki documentation on those components as a starting point:

- [xSPInstallPrereqs](https://github.com/PowerShell/xSharePoint/wiki/xSPInstallPreReqs)
- [xSPInstall](https://github.com/PowerShell/xSharePoint/wiki/xSPInstallPreReqs)

**Comment by BrianFarnhill** [comment]
This is now in PR #191 and will be merged in to dev once it is reviewed

**Comment by BrianFarnhill** [comment]
This just got merged in to dev, closing this issue
