### ISSUE TITLE
Create new xSPContentDatabase resource

### ISSUE THREAD

**Issue by ykuijs** [PowerShell/xSharePoint#201]
Currently we have no way to manage the settings of content databases or to add/remove databases to web applications. We need a resource to be able to manage these.

When the content database is not yet added to the web application and Ensure=Present, the resource adds the database to the web application.
When the content database is already added, the resource makes sure the settings are configured as specified.
When Ensure=Absent and the content database is added to the web application, the content database is dismounted.

I think this resource should not be used to attached content databases from older version of SharePoint. That is more of a migration scenario, which to my opinion isn't a scenario I would like to handle using DSC. But am open for a discussion if someone thinks otherwise :-)

xSPContentDatabase ContentDB {
    Name                    = "SharePoint_Content_01"
    DatabaseServer    = "SQL.contoso.local\SQLINSTANCE" 
    WebAppUrl            = "http://sharepoint.contoso.com"
    Enabled                 = $true
    WarningSiteCount     = 2000
    MaximumSiteCount   = 5000
    AssignNewDatabaseId  = $true
    Ensure                           = "Present"
    PsDscRunAsCredential = $InstallAccount
}

**Comment by BrianFarnhill** [comment]
Happy to see this one go in as long as we make sure that in the event of saying "Ensure = Absent" that we only dismount the content database - under no circumstances do I want to see us automatically delete data as part of a configuration. You wanna take this one now or just leave it in the back log?

**Comment by ykuijs** [comment]
1000% agree! Never automatically delete data!

Sure, put it on my name. Am working on completing the WebAppPolicy first, after that I will start this one.

**Comment by ykuijs** [comment]
This issue can be closed, since it is merged into Dev
