### ISSUE TITLE
Question about the example files

### ISSUE THREAD

**Issue by jmcanally** [PowerShell/xSharePoint#203]
I'm lost as to how to use the example files.  Shouldn't there be a PSM1 file to accompany the PSD1?

**Comment by BrianFarnhill** [comment]
No, the example files will run and generate your MOF file for you based on the parameters in the PSD1 file. Are you seeing a specific error or anything like that?

**Comment by jmcanally** [comment]
That's the odd part, no error.  I just get an empty folder named SharePointServer with no MOF.  Nothing in the event logs either.  I'm certain there's a step I'm missing, here's my steps so far...

 - Download latest dev version of xSharePoint
 - Change file properties on ZIP as to Unblock
 - Extract contents of Modules folder to Powershell modules folder (ex: c:\prog files\powershell\modules)
 - Open powershell window and change directories to Examples folder
 - Pull in SharePointServer.ps1 with dot source command
 - Run SharePointServer function in Powershell window
 - Enter credentials for each parameter when prompted
 - Powershell window returns with no error
 - Empty SharePointServer folder in the Examples folder.

What am I missing?

**Comment by BrianFarnhill** [comment]
When you call SharePointServer you need to add the ConfigurationData property to tell it where the PSD1 file is, it won't know where it is by default and without it you get no output.

    SharePointServer -ConfigurationData '.\Single Server\SharePoint.psd1'

Keep in mind that by default you'll see errors here about encrypting credentials unless you add certificate details to the example, or tell it to allow plain text passwords. I'll leave this item open so I can track this and get the examples updated to have some comments and examples of both in there to make them more straight forward.

**Comment by jmcanally** [comment]
So the switch for ConfigurationData is exactly what I was missing.  After adding that I was able to generate the MOF as expected.  Thanks for the help and the quick response.

**Comment by ykuijs** [comment]
@BrianFarnhill Can't this issue be closed, since the question was answered?
