### ISSUE TITLE
xSPCacheAccounts not adding claims identity

### ISSUE THREAD

**Issue by mariusv-msft** [PowerShell/xSharePoint#205]
The current xSPCacheAccounts resource doesn't add the correct user identity to the web application policy when utilizing claims for a specific web application.

**Comment by harbars** [comment]
if ($wa.UseClaimsAuthentication) {
            $SuperReaderAlias = "i:0#.w|$params.SuperReaderAlias"
            $SuperUserAlias = "i:0#.w|$params.SuperUserAlias"
        } else {
            $SuperReaderAlias = $params.SuperReaderAlias
            $SuperUserAlias = $params.SuperUserAlias
        }
        
        
        
        if ($wa.Properties.ContainsKey("portalsuperuseraccount")) { 
            $wa.Properties["portalsuperuseraccount"] = $SuperUserAlias
        } else {
            $wa.Properties.Add("portalsuperuseraccount", $SuperUserAlias)
        }
        if ($wa.Properties.ContainsKey("portalsuperreaderaccount")) { 
            $wa.Properties["portalsuperreaderaccount"] = $SuperReaderAlias
        } else {
            $wa.Properties.Add("portalsuperreaderaccount", $SuperReaderAlias)
        }
        
        #  note that the if else on the property already existing is redundant. 
        # if the property doesn't exist you don't actually need to call Add()
        # just setting it will create it so you can do this instead:
        
        $wa.Properties["portalsuperuseraccount"] = $SuperUserAlias
        $wa.Properties["portalsuperreaderaccount"] = $SuperReaderAlias

**Comment by BrianFarnhill** [comment]
I forgot to mark this as in progress - I have a fix in #234 

@harbars Thanks for the pointers, ill work that in to the branch i have open there and test in my lab this afternoon

**Comment by harbars** [comment]
cool. at some point i'll get my noggin round all this github shenanigans....

**Comment by BrianFarnhill** [comment]
This has been merged in to dev, closing this issue
