### ISSUE TITLE
xSPVisioServiceApp does not work on PowerShell 4

### ISSUE THREAD

**Issue by BrianFarnhill** [PowerShell/xSharePoint#208]
xSPVisioServiceApp will not work on machines that have PowerShell 4 (only PowerShell 5, using the PsDscRunAsCredential attribute) as it does not have an InstallAccount property in its schema. This should be added to allow the backwards compatibility to work correctly.

**Comment by caadam** [comment]
I'll look a this tonight

**Comment by camiloborges** [comment]
Hey. Can you also add the $Ensure please?


   [Required, Description("Present ensures the URL is set for this zone on this web app, Absent ensures it is removed"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] string Ensure;
    [Write, Description("POWERSHELL 4 ONLY: The account to run this resource as, use PsDscRunAsAccount if using PowerShell 5"), EmbeddedInstance("MSFT_Credential")] String InstallAccount;

**Comment by BrianFarnhill** [comment]
@caadam @camiloborges Leave the ensure parameter, I'm doing that in a big run through for issue #148 - just get the install account in as its own change for this one thanks

**Comment by caadam** [comment]
Changes made @BrianFarnhill , time for a good'ol fashion code review.

**Comment by BrianFarnhill** [comment]
This one is in #227 just pending review

**Comment by BrianFarnhill** [comment]
Merged in to dev, closing this issue
