### ISSUE TITLE
xSPUserProfileSyncConnection fails due to incorrect permissions

### ISSUE THREAD

**Issue by andy-cox** [PowerShell/xSharePoint#214]
The account used to access the UserProfileConfigManager does not have the correct permissions causing the creation of the sync connection to fail. Adding the the admin/install account manually, to the UPSA admins and permissions with full control, in Central Admin seems to resolve this problem and the connection can be created successfully.

The errors i'm getting:

Admin/install account not got Full Control permissions:
```powershell
PowerShell DSC resource MSFT_xSPUserProfileSyncConnection  failed to execute Test-TargetResource functionality with error message: Exception calling ".ctor" with "1" argument(s): "UserProfileApplicationNotAvailableException_Logging :: 
UserProfileApplicationProxy.ApplicationProperties ProfilePropertyCache does not have ad9....e56b661f" 
    + CategoryInfo          : InvalidOperation: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : HAL
```

Admin/install account got permissions but not an admin of the UPSA:
```powershell
PowerShell DSC resource MSFT_xSPUserProfileSyncConnection  failed to execute Set-TargetResource functionality with error message: You cannot call a method on a null-valued expression. 
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : HAL
```

**Comment by BrianFarnhill** [comment]
Hey @andy-cox - I'm working on xSPServiceAppSecurity as we speak which will allow us to script adding to the service app permissions like that, so when that is ready we can use that to resolve this issue in a better way. I'll look in to whether or not we need a check for this inside the user profile sync resource though to through a more meaningful error.

**Comment by BrianFarnhill** [comment]
@andy-cox If you want to take a look at my first cut of this one, its [in my repo](https://github.com/BrianFarnhill/xSharePoint/tree/feature-serviceappsecurity/Modules/xSharePoint/DSCResources/MSFT_xSPServiceAppSecurity)

I still need to write my unit tests to make sure my logic all makes sense, but I've used it to add some accounts to my test environment through the MembersToInclude property successfully, so at least that much does work.

**Comment by camiloborges** [comment]
We used to have a test under user profile property for that very same permissions issue. We might ened to included that in the user profile connection too.
https://github.com/PowerShell/xSharePoint/blob/2b497fcef4465634b1af4a3a1a4630902cda8700/Modules/xSharePoint/DSCResources/MSFT_xSPUserProfileProperty/MSFT_xSPUserProfileProperty.psm1#L179

**Comment by BrianFarnhill** [comment]
@camiloborges Agreed, lets get that same test in to the user profile sync resource as well

@andy-cox The resource to set the permissions is now sitting in PR #220 and will be merged in to dev as soon as one of my guys code reviews it.

**Comment by BrianFarnhill** [comment]
Merged in to dev, closing this issue
