### ISSUE TITLE
Add xSPDesignerSettings resource

### ISSUE THREAD

**Issue by BrianFarnhill** [PowerShell/xSharePoint#23]
The xSPDesignerSettings resource will configure SharePoint Designer Settings for the farm or a specific site collection. It should be structured as follows:

xSPDesignerSettings MainWebAppSPDSettings
{
    Url = "https://intranet.sharepoint.contoso.com"
    Scope = "WebApplication"
    EnableSPD = $false
    AllowDetachPages = $false
    EnableMasterPageCustomise = $false
    EnableHiddenFolderStructure = $false
}

The scope here should be "WebApplication" or "SiteCollection" and it can then apply the settings to the relevant target.

**Comment by ykuijs** [comment]
I am working on it!

**Comment by ykuijs** [comment]
The object model has some additional configuration options, which are not available via the GUI. Shall I add these as well?

AllowCreateDeclarativeWorkflow
AllowSavePublishDeclarativeWorkflow
AllowSaveDeclarativeWorkflowAsTemplate

**Comment by BrianFarnhill** [comment]
Yes i think so - are these same options available when applying to a web app as well as within a site collection? If not we just need to make sure we throw a meaningful error about the misuse of the parameters

**Comment by ykuijs** [comment]
Yes, they are. Will add these as well.

**Comment by ykuijs** [comment]
Updated structure:
xSPDesignerSettings MainWebAppSPDSettings
 {
 Url = "https://intranet.sharepoint.contoso.com"
 Scope = "WebApplication"
 AllowSharePointDesigner = $false
 AllowDetachPagesFromDefinition = $false
 AllowCustomiseMasterPage = $false
 AllowManageSiteURLStructure = $false
 AllowCreateDeclarativeWorkflow = $false
 AllowSavePublishDeclarativeWorkflow = $false
 AllowSaveDeclarativeWorkflowAsTemplate = $false
}

I also renamed some properties so naming is consistent.

**Comment by BrianFarnhill** [comment]
Sounds good dude, make it so :)

**Comment by ykuijs** [comment]
@BrianFarnhill - I think this issue can be closed, since the resource was already created.
