### ISSUE TITLE
Farm Passphrase as secure string

### ISSUE THREAD

**Issue by MikeLacher448** [PowerShell/xSharePoint#230]
Use a PSCredential object to hold the farm passphrase. The secure string portion of the credential would be referenced as:  
 Passphrase = ($params.Passphrase).Password

**Comment by MikeLacher448** [comment]
Brain, please assign this one to me as we discussed.

**Comment by BrianFarnhill** [comment]
@MikeLacher448 All your Mike

Quick question though, wouldn't you refer to it as:

    Passphrase = ($params.Passphrase).GetNetworkCredential().Password

**Comment by MikeLacher448** [comment]
For the plaintext version, but the SharePoint candler takes that as a secure string if I'm recalling correctly. I'll double check.

**Comment by BrianFarnhill** [comment]
@MikeLacher448 It does, we shift it across to a secure string before we pass it in, but from memory I saw that password value coming back as null a bunch of times. If it works, then absolutely do it your way - I just wanted to check :)

**Comment by MikeLacher448** [comment]
since it's in the same resource, I'm also going to add support for installing Central Admin with Kerberos authentication

**Comment by BrianFarnhill** [comment]
This was merged in #238 - closing this issue
