### ISSUE TITLE
Add xSPSubscriptionSettingsServiceApp resource

### ISSUE THREAD

**Issue by BrianFarnhill** [PowerShell/xSharePoint#24]
The xSPSubscriptionSettingsService resource is used to create a new subscription settings service application and proxy. It will be structured as follows:

xSPSubscriptionSettingsServiceApp SubscriptionSettingsServiceApp
{
    Name = "Subscription Settings Service Application"
    AppPool = "SharePoint web services"
    DatabaseServer = "SQL01.contoso.com"
    DatabaseName = "SP_ManagedMetadata"
}

**Comment by BrianFarnhill** [comment]
@camiloborges here is the reference to the subscription settings app that you asked about

**Comment by camiloborges** [comment]
Cool. 

Assign me to this one too.

**Comment by BrianFarnhill** [comment]
This is part of PR #108 and is now merged, closing this issue
