### ISSUE TITLE
Latest merge of xSPJoinFarm has introduced an issue

### ISSUE THREAD

**Issue by ykuijs** [PowerShell/xSharePoint#240]
In MSFT_xSPJoinFarm.schema.mof on line 23, the parameter declaration contains two closing brackets:

[Required, Description("The passphrase that should be used to join the farm") , EmbeddedInstance("MSFT_Credential")**]]** string Passphrase;

**Comment by BrianFarnhill** [comment]
Good catch, just merged your fix in. Closing this issue.
