### ISSUE TITLE
option to install features from SXS files on xSPInstallPrereqs

### ISSUE THREAD

**Issue by MikeLacher448** [PowerShell/xSharePoint#243]
On a completely closed network, PreReq installer is not able to install all required features in offline mode. The bits for some features are not installed on the OS, and are downloaded from Windows Update as needed. Add-WindowsFeature supports a Source parameter for environments that have no connectivity to Windows Update.

Will add an optional SXSsource parameter to xSPInstallPrereqs. If specified, the resource will install required features using add-WindowsFeature prior to running the prerequisiteinstaller executable.

**Comment by BrianFarnhill** [comment]
@MikeLacher448 Sounds good - the previous work around was to just use the "WindowsFeature" resource before the prereq installer as that could use a source parameter, but I agree that we should wrap it up in here as well.

**Comment by BrianFarnhill** [comment]
This was merged in #259 - closing this issue
