### ISSUE TITLE
xSPInstallPrereqs error 4252 The Verbose key is not a valid property in the corresponding DSC resource schema file

### ISSUE THREAD

**Issue by BrunoReboul** [PowerShell/xSharePoint#244]
The results from Get-TargetResource must be in a Hashtable format.
$Results contains $PSBoundParamters that is a dictionary not a hashtable.
It contains an additionnal key "Verbose", not specified in the MOF file
Proposed fix in replacement of lines 88 to 95:

    if (($returnValue.Values | Where-Object { $_ -eq $false }).Count -gt 0) {
        $Ensure = "Absent"
    } else {
        $Ensure = "Present"
    }
    
    $Results = @{
        Ensure            = $Ensure
        InstallerPath     = $InstallerPath
        OnlineMode        = $OnlineMode
        SQLNCli           = $SQLNCli
        PowerShell        = $PowerShell
        NETFX             = $NETFX
        IDFX              = $IDFX
        Sync              = $Sync
        AppFabric         = $AppFabric
        IDFX11            = $IDFX11
        MSIPCClient       = $MSIPCClient
        WCFDataServices   = $WCFDataServices
        KB2671763         = $KB2671763
        WCFDataServices56 = $WCFDataServices56
    }

    return $results

Configuration used = Windows Server 2012 R2 / Sharepoint 2013 SP1 Enterprise

**Comment by BrianFarnhill** [comment]
I have a fix for this in #246 - Ill close this off once it's been put in to dev.

**Comment by BrianFarnhill** [comment]
Merged this in to dev, closing this issue
