### ISSUE TITLE
xSPInstallPrereqs does not trigger a reboot each time it is needed

### ISSUE THREAD

**Issue by BrunoReboul** [PowerShell/xSharePoint#245]
xSPInstallPrereqs does not trigger a reboot each time it is needed

In complement to existing code in Set-TargetResource why not to add at the end of the procedure:

return (((Get-Item 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Component Based Servicing\RebootPending' -ErrorAction SilentlyContinue) -ne $null) -or ((Get-Item 'HKLM:\Software\Microsoft\Windows\CurrentVersion\WindowsUpdate\Auto Update\RebootRequired' -ErrorAction SilentlyContinue) -ne $null) -or ((Get-Item 'HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager' | Get-ItemProperty).PendingFileRenameOperations.count -gt 0))

Asking so to DSC to trigger a reboot when a reboot pending is detected

**Comment by BrianFarnhill** [comment]
@BrunoReboul Great idea, will get something like that implemented in it shortly.

**Comment by BrianFarnhill** [comment]
This is in pull request #246 - ill close this issue off once it is merged in to dev

**Comment by BrianFarnhill** [comment]
Merged this in to dev, closing this issue
