### ISSUE TITLE
xSPUsageApplication Get-TargetResource hash table not aligned with mof definition

### ISSUE THREAD

**Issue by BrunoReboul** [PowerShell/xSharePoint#248]
Error 4252 on Get-TargetResource due to 2 field in the returned hash table 'DatabasePassword' and 'DatabaseUsername' that are missing in the mof definition of xSPUsageApplication.

Proposed solution : remove the 2 fields from the hashtable, (IMO sending back the password iin a string not desirable). Solution tested / works well

Alternate solution, update the mof definition to be aligned.

**Comment by BrianFarnhill** [comment]
Thanks for reporting this - there was a change a while back that swapped those two fields for the PSCredential object $DatabaseCredentials that is there now, and it looks like we missed that hashtable. We'll drop those from the results and replace with the DatabaseCredentials property that will just pass through the PSCredential it's passed in (if any)

**Comment by BrianFarnhill** [comment]
The fix for this is in #253 - I'll close this when the change hits dev

**Comment by BrianFarnhill** [comment]
Just merged this in, closing this bug
