### ISSUE TITLE
Add xSPWorkManagementServiceApp resource

### ISSUE THREAD

**Issue by BrianFarnhill** [PowerShell/xSharePoint#25]
The xSPWorkManagementServiceApp resource will provision the work management service application. It should be structured as per below:

xSPWorkManagementServiceApp WorkManagementServiceApp
{
    Name = "Work Management Service Application"
    Ensure = "Present"
    AppPool = "SharePoint Web Services"
}

This cmdlet should also create/remove a proxy object as well as the main service app.

**Comment by camiloborges** [comment]
Didn't Microsoft ditch this service app ? If so we might be better off closing this one

**Comment by BrianFarnhill** [comment]
Still supported in SharePoint 2013 (but it's not in 2016) so I still think it needs to be done.

**Comment by camiloborges** [comment]
ok, I am on it. https://github.com/camiloborges/xSharePoint/commit/680cc21eed988226aebe2db1cf8d290c98f49be3

**Comment by camiloborges** [comment]
it needs to take the Set-WorkMa.. cmLet parameters.
Reference
https://technet.microsoft.com/EN-US/library/fp161253.aspx

**Comment by BrianFarnhill** [comment]
This was released in v0.10 - closing now
