### ISSUE TITLE
new resource xSPIrmSettings for RMS integration

### ISSUE THREAD

**Issue by MikeLacher448** [PowerShell/xSharePoint#262]
New resource to integrate SharePoint with AD RMS, same settings that are on IrmAdmin.aspx in Central Admin.

xSPIrmSettings 
{
 Ensure = "Present"                                enables / disables IRM
 UseADRMS = $true / $false                  uses the RMS published in AD
 RMSserver = "https://ADRMS.fqdn"      specify RMS server
}

**Comment by BrianFarnhill** [comment]
@MikeLacher448 Consider it on the backlog - are you working on this now or did you just want to raise this for us to keep in the backlog to look at later?

**Comment by MikeLacher448** [comment]
One I'm working on now for my customer. I should have a pull request with this by mid week.

**Comment by BrianFarnhill** [comment]
Too easy - tagging as in progress, it's all yours. Thanks @MikeLacher448

**Comment by camiloborges** [comment]
btw: that is a nice addition :)

**Comment by ykuijs** [comment]
This issue can be closed off. This has been merged in PR 270

**Comment by ykuijs** [comment]
@BrianFarnhill Short reminder: This issue can be closed, it was merged in PR270
