### ISSUE TITLE
Add xSPVisioServiceApp resource

### ISSUE THREAD

**Issue by BrianFarnhill** [PowerShell/xSharePoint#27]
The xSPVisioServiceApp resource will be sued to provision a new Visio services service application. It should be structured as per below.

xSPVisioServiceApp VisioServices
{
    Name = "Visio Services Service Application"
    Ensure = "Present"
    AppPool = "SharePoint Web Services"
}

**Comment by NikCharlebois** [comment]
FYI - I will be taking this one over tomorrow

**Comment by BrianFarnhill** [comment]
All yours @NikCharlebois - thanks bud

**Comment by NikCharlebois** [comment]
Pull Request submitted

**Comment by BrianFarnhill** [comment]
Its PR #109 for those playing along at home :)

**Comment by BrianFarnhill** [comment]
This was merged in PR #111 - closing this as complete
