### ISSUE TITLE
Contribution guidelines should point to common guidelines under DscResources repo

### ISSUE THREAD

**Issue by KarolKaczmarek** [PowerShell/xSharePoint#271]
We should have consistent contribution process across all DscResources repositories and we should point users to the common documents for guidelines: https://github.com/PowerShell/DscResources/blob/master/CONTRIBUTING.md
This way if there are any changes, we can update that information in a single place and are sure all repos point to the same guidelines. 

Currently xSharePoint has separate wiki page for contribution instructions which contains identical or very similar information as the CONTRIBUTING.md. Instead, we should link to that document and if there are any additional guidelines specific for xSharePoint repo only (normally those shouldn't be needed, so we should have a good reason for that), they can be added in addition to that.

**Comment by BrianFarnhill** [comment]
@KarolKaczmarek Agree, I'll update the wiki page with the xSharePoint specific bits and refer to the main document for the rest.

**Comment by BrianFarnhill** [comment]
@KarolKaczmarek This is done now, check it out at https://github.com/PowerShell/xSharePoint/wiki/Contributing-to-xSharePoint 

Closing this one off
