### ISSUE TITLE
Sharepoint is using an old version of DSCResource.Tests

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/xSharePoint#275]
Before submitting an issue to this project, please take a moment to provide the following details if possible:

- [x ] Is this a bug request or an enhancement request? no
- [N/A ] Version of PowerShell the DSC Target Node is running.
- [N/A ] Operating system the DSC Target Node is running.
- [X] Version of this DSC resource you're using. : https://github.com/PowerShell/xSharePoint/pull/272 
- [X] Details of the error that is occurring., none, tests are missing.
- [N/A ] The DSC configuration that is using the resource.

Thank you for contributing.
Your feedback and support is greatly appreciated.

If you are able to resolve this issue or add new features, you may submit a Pull Request against this project.
Please see the [Contribution Guideliness](https://github.com/powershell/xSharePoint/wiki/Contributing%20to%20xSharePoint) for information on how to contribute.

**Comment by BrianFarnhill** [comment]
Funny you should mention this - I'm working on it as we speak after I spoke to @KarolKaczmarek 

I've got the tests running, I need to resolve the new failures before I commit. Will close this off after it's merged in to dev from [my branch](https://github.com/BrianFarnhill/xSharePoint/tree/feature-dsctestintegration)
