### ISSUE TITLE
xSPWebAppGeneralSettings not properly handling SecurityValidationTimeoutMinutes

### ISSUE THREAD

**Issue by MikeLacher448** [PowerShell/xSharePoint#280]
_Please provide the following information regarding your issue (place N/A if certain fields don't apply in your case:_

**Details of the scenario you try and problem that is occurring:**
When specifying a value for SecurityValidationTimeoutMinutes, the value isn't making it to the Set-TargetResource and is being set to 0, breaking security validation.

**The DSC configuration that is using the resource:**
the issue is within the xSPWebAppGeneralSettings resource.

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Win2012R2, WMF4

**Version of the DSC module you're using:**
dev branch

this is a result of changes I made to the resource in a prior pull request. I will fix and submit a new PR within the next day or so. I think I just messed up with the way I manipulate the parameter before it's passed into invoke-xSharePointCommand, should be an easy fix.

_Please see the [Contribution Guideliness](https://github.com/powershell/xSharePoint/wiki/Contributing%20to%20xSharePoint) for information on how to contribute._

**Comment by BrianFarnhill** [comment]
All yours @MikeLacher448 - Thanks for reporting it!

**Comment by BrianFarnhill** [comment]
Fixed in #280 - Closing this off
