### ISSUE TITLE
Trust between different SP farms

### ISSUE THREAD

**Issue by tonyhxh** [PowerShell/xSharePoint#291]
Is there a plan to provide trust between different SP farms, and in terms service applications can be published from a service farm, and consumed by a content farm. 

Thanks
Tony Huang

**Comment by ykuijs** [comment]
Hi Tony,

This is being discussed in issue #239. There are some challenges which we need to figure out before implementing this functionality. But it is definitely on the roadmap.

Regards, Yorick

**Comment by BrianFarnhill** [comment]
Thanks for responding @ykuijs 

@tonyhxh - as Yorick mentioned, check the other issue for discussion on this. Closing this one off as a duplicate. Thanks guys
