### ISSUE TITLE
Skip configuration upon error

### ISSUE THREAD

**Issue by jmcanally** [PowerShell/xSharePoint#292]
**Details of the scenario you try and problem that is occurring:**
Is there a way to skip the configuration of a node if an error occurs?  Ideally I'd like to process each node and only skip the nodes that have errors along the way.

I've tried processing each node with a separate Start-DSCConfiguration command but if there's an exception all processing stops.

One use case would, perhaps there's an error installing the pre-reqs on a single server but the rest of the server install/configure just fine.  Is it possible to complete the configuration of the healthy nodes while skipping the sick?  I realize this isn't a typical function of DSC but I was hoping for some duck tape.

**The DSC configuration that is using the resource:**
Here's an example of the behavior I'm looking for.

- Node1
  - Resource 1 - succeeds
  - Resource 2 - succeeds
  - Resource 3 - succeeds

- Node2
  - Resource 1 - error occurs, skip to next node
  - Resource 2 - skipped
  - Resource 3 - skipped

- Node3
  - Resource 1 - succeeds
  - Resource 2 - succeeds
  - Resource 3 - succeeds

**Version of the Operating System and PowerShell the DSC Target Node is running:**
N/A

**Version of the DSC module you're using:**
N/A

**Comment by BrianFarnhill** [comment]
@jmcanally I'm not quite sure I follow what you're asking for here, but have you checked out the WaitForAll resource that is in PowerShell 5? You can use it to tell a node to wait for the successful completion of a specific resource on a remote computer, and it can then be a dependency for a specific computer. One use case that I use this for is to tell servers to not attempt to join a farm (using xSPJoinFarm) until xSPCreateFarm has completed successfully on the first node. Is this the sort of thing you need?

**Comment by jmcanally** [comment]
@BrianFarnhill Thanks for the tip, that worked.
