### ISSUE TITLE
xSPUsageApplication + Proxy

### ISSUE THREAD

**Issue by brussell41** [PowerShell/xSharePoint#294]
Ran into an issue where when deploying a SharePoint farm using DSC, the Search Service Application components weren't starting; the infamous "unable to retrieve topology component health states" notification.  Upon research, it was determined to be because the Usage Application Proxy was not started. 

When reviewing the xSPUsageApplication module, I noticed it was missing two lines where the Usage Application Proxy is provisioned:

$UP = Get-SPServiceApplicationProxy | where {$_.TypeName -like "Usage*"}
$UP.Provision()

Can we get this added to the xSPUsageApplication module?

**Comment by BrianFarnhill** [comment]
Hey @brussell41 - thanks for reporting. We had this reported in #241 and the fix is in the dev branch to be included in our next release!

**Comment by brussell41** [comment]
That's great. Thank you for your response!
Keep up the great work!

Get Outlook for iOS




On Tue, May 10, 2016 at 8:43 PM -0700, "Brian Farnhill" <notifications@github.com> wrote:












Closed #294.
