### ISSUE TITLE
Support partitioned provision mode

### ISSUE THREAD

**Issue by avishnyakov** [PowerShell/xSharePoint#295]
We heavily use partitioned / multi-tenancy SharePoint 2013 / 2016 setup and would be keen to see that support in xSharePoint. 

I know that AutoSPInstaller does not support partitioned mode provision, so putting it here to see how it might fit into xSharePoint and further roadmap.

**Comment by BrianFarnhill** [comment]
Hi @avishnyakov, currently we have no intention to support multi-tenancy in any capacity. It adds a lot of complexity in terms of what we need to do with testing to maintain working resources, and given the relatively small number of customers who use this in SharePoint as a whole it was decided that we wouldn't do this either.

**Comment by avishnyakov** [comment]
Alright, I see the point, fair enough. 

@BrianFarnhill, could you at least guide over the effort required?
In case we would be able to help with adding multi-tenancy support, testing and maintenance, curious to see if this could be an option at all.

**Comment by BrianFarnhill** [comment]
Given the potential for complexity to increase the amount of logic and code in the resources themselves I really don't want to push this in at all. It will make managing and making changes to the resources more difficult for other content authors. I appreciate that you could build them in, but it's something that essentially becomes technical debt for other contributors as they need to try to not break any of that added logic when making other changes.

**Comment by camiloborges** [comment]
I know I am often very pedantic...
On-Prem environments really don't do very well with multi tenancy.
It wasn't really designed for that. Multi tenancy was designed for Online.
There are so many things that can go wrong that I am happy to explicitly include in the documentation that this will not be supported. 

It is just a bad idea....  It does work, but simply not worth the effort

Camilo Borges
Mob:0488 056 964
Sent via iPhone while out and about

**Comment by avishnyakov** [comment]
Arhh.. make sense, make sense @BrianFarnhill 
In that case I think we'll craft our own DSC bits to address our problems.

@camiloborges, what exactly is meant by on-prem environments don't do very well with multi-tenancy? Some companies are software companies, hosting or service provider companies which host their own  offers on top of multi-tenancy deployments. Having same challenges around CD/DevOps, considering DSC or other CM tools. Could you please elaborate on what's so wrong with that and what are exact issues with having multi-tenancy?

**Comment by camiloborges** [comment]
Ok... I am taking a fair bit of time to think about this.
- On-Prem to me is limited to a company that hosts SharePoint for themselves. hosters is in a different category. 
- Few hosters around the globe with many clients don't mean a lot to me. It doesn't mean it isn't relevant for hosters, but not relevant for enterprises. 
- Multi-Tenancy it is certainly a degree of complexity that is far too much for the vast majority.
- Adding Partitioned parameter to services is just one piece of the puzzle. 

I am not saying Multi Tenancy doesn't work, but I am saying that I'd rather not encourage it to be used.

I take back the comment that it is a bad idea. It isn't a bad idea nor an invalid question. It is worthwhile asking, but yet, not something I see this project covering in the near future.

We have a similar discussion going on with Shared Services.  If we are to support that, we need to have a solution for everything there is to multi tenancy.

**Comment by avishnyakov** [comment]
Alright, thanks guys. All good.

**Comment by camiloborges** [comment]
Hello.
I've slept on this for a while and I am changing my take on this idea..
I believe that we can definitely support it. It is an important piece of functionality for hosters. And Hosters would actually end up having to really stress the solution.
@BrianFarnhill : need your input on this again :)
@avishnyakov , Could you outline what are the other resources we would need in order to achieve it? If we can plan this nicely we should be able to add the partitionedmode (or partitionMode ) to the the service apps.
