### ISSUE TITLE
Add xSPAppManagementServiceApp resource

### ISSUE THREAD

**Issue by BrianFarnhill** [PowerShell/xSharePoint#34]
The xSPAppManagementServiceApp resource is used to create a new app management service application and proxy. It will be structured as follows:

xSPAppManagementServiceApp AppManagementServiceApp
{
    Name = "App Management Service Application"
    AppPool = "SharePoint web services"
    DatabaseServer = "SQL01.contoso.com"
    DatabaseName = "SP_ManagedMetadata"
}

**Comment by camiloborges** [comment]
Question: Should we allow more than 1 app management app per farm?

**Comment by BrianFarnhill** [comment]
1) in terms of this resource, does it matter? We'll just be creating instances of the service app - I don't see a lot of reasons to need more than one, but I also don't see the harm. Thoughts?
2) No, use xSPServiceInstance for this
3) Yes we still need this - can you include it here?
4) No we dont and I don't have it in my pipeline - how are you imagining this would work?

**Comment by camiloborges** [comment]
1) No harm, but, does SP work with multiple app mgmt services? If the answer is no we can just ignore the name and always ensure there is only one service. 
2) tick. closed.
3) deal.
4) I have scripts to set it up. The only  issue is that it needs a path to a SSL certificate, and it is currently using an 'invalid valid' cert using makecert. Only relevant if xSharePoint supports high-trust apps

**Comment by BrianFarnhill** [comment]
@camiloborges I definitely want to make sure we can deploy high trust apps, but there are a few things we'll need to look at with this one, like how we make sure the cert is on all of the servers and then how we register it. It could be a separate resource though to do that kind of work though - if we need to pass the certificates password to install it from a PFX (need to check if we can use a CER for that, I'm hazy off the top of my head) then we'll need to do something to ensure it gets protected in the MOF file. Otherwise we can work on the basis that we just look for a cert with a specific thumbprint and make sure it gets installed by other means?

**Comment by BrianFarnhill** [comment]
This is part of PR #108 and is now merged, closing this issue
