### ISSUE TITLE
Add xSPUserProfileSyncConnection resource

### ISSUE THREAD

**Issue by BrianFarnhill** [PowerShell/xSharePoint#38]
The xSPUserProfileSyncConnection resource defines a specific connection that should be defined in the user profile service application specified on the farm. This maps to the Add-SPProfileSyncConnection cmdlet and should surface all of its options. It should be structured as follows:

xSPUserProfileSyncConnection MainDomain
{
    UserProfileService = "User Profile Service Application"
    ConnectionForest = "contoso.com"
    ConnectionDomain = "Contoso"
    ConnectionCredentials = $connectionCredential
    ConnectionOU = "OU=SharePoint Users,DC=Contoso,DC=com"
}

**Comment by camiloborges** [comment]
hello.

should we use Add-SPProfileSyncConnection? Is It Supported?

**Comment by BrianFarnhill** [comment]
Not supported outside of SharePoint Online as far as I'm aware, so I wanna try to find a way to get around it, we might need to use the server side object model in script to fill this functionality out right. Happy to hear your ideas.

**Comment by camiloborges** [comment]
Last I heard there was no supported way of creating sync connections.
I scripted it earlier on this year but I am under the impression we didn't use the script because of that.

So, question to MS: is there a supported way of creating sync connections? :)

**Comment by camiloborges** [comment]
I can't find the script I've written for that, but I am pretty sure I used this method here (Uses cnnMgr.AddActiveDirectoryConnection)

http://community.obilogic.co.uk/blogs/teamblog/archive/2015/04/20/sharepoint-2013-migrate-replicate-user-profile-service-application-configuration-between-farms-using-powershell-part-1.aspx

**Comment by BrianFarnhill** [comment]
@camiloborges you are correct, the blog post you have there looks like the way to do it. At a quick glance all of the API calls there are public methods, so we are fine from a support perspective on this one. I'll confirm this to be sure and let you know if there are any issues but to the best of my knowledge we'll be fine.

**Comment by camiloborges** [comment]
hey @BrianFarnhill  please mark this as in progress

**Comment by BrianFarnhill** [comment]
All yours @camiloborges

**Comment by camiloborges** [comment]
Hello. 
Updated schema: 
 [ClassVersion("1.0.0.0"), FriendlyName("xSPUserProfileSyncConnection")]
class MSFT_xSPUserProfileSyncConnection : OMI_BaseResource
{
    [Key] string Name;
    [Required] string Forest;
    [Required] string UserProfileService;
    [Required, EmbeddedInstance("MSFT_Credential")] String Credentials;
    [Write, EmbeddedInstance("MSFT_Credential")] String InstallAccount;
    [Required] string IncludedOUs[];
    [write] string ExcludedOUs[];
    [write] string Server;
    [Write] boolean  UseSSL;
    [Write] boolean  Force;
    [Write] string ConnectionType ;
};

Force is just so resource can delete and recreate connection in case the forest is different.

**Comment by BrianFarnhill** [comment]
@camiloborges Can we be more specific on the Credentials property to be something like "ConnectionCredential" - that way its clear what its there for

**Comment by camiloborges** [comment]
I can certainly do that. I tried to shorten parameters name but some do need to be a bit more specific

**Comment by BrianFarnhill** [comment]
Lets go for longer names over ambiguous any time it comes up - thanks bud

**Comment by camiloborges** [comment]
any request on the other attributes?

**Comment by BrianFarnhill** [comment]
Should connection type be a fixed list of options there? The others seem obvious enough I think.

**Comment by camiloborges** [comment]
good point @BrianFarnhill . it should then be

[ClassVersion("1.0.0.0"), FriendlyName("xSPUserProfileSyncConnection")]
class MSFT_xSPUserProfileSyncConnection : OMI_BaseResource
{
    [Key] string Name;
    [Required] string Forest;
    [Required] string UserProfileService;
    [Required, EmbeddedInstance("MSFT_Credential")] String ConnectionCredentials;
    [Write, EmbeddedInstance("MSFT_Credential")] String InstallAccount;
    [Required] string IncludedOUs[];
    [write] string ExcludedOUs[];
    [write] string Server;
    [Write] boolean  UseSSL;
    [Write] boolean  Force;
      [Write, ValueMap{"ActiveDirectory","BCS"}, Values{"ActiveDirectory","BCS"}] string ConnectionType ;
    
};
BCS might have to be changed to something else. I won't implement it right now, but I will makesure the ValueMap is correct.

**Comment by BrianFarnhill** [comment]
Put the BCS option in and have it throw an exception to say its not implemented yet. Add an issue here to state that it doesn't work and I'll tag it as technical debt for us to come back to later.

**Comment by BrianFarnhill** [comment]
Released in v0.10 - closing this issue
