### ISSUE TITLE
Add xSPUserProfileProperty resource

### ISSUE THREAD

**Issue by BrianFarnhill** [PowerShell/xSharePoint#39]
The xSPUserProfileProperty resource is used to create/update user profile properties, specifying what is editable as well as sync details. It should be structured as per the below example:

xSPUserProfileProperty WorkEmailProperty
{
    Name = "WorkEmail"
    DisplayName = "Work Email"
    Type = "Email"
    Description = ""
    PolicySetting = "Required"
    PrivacySetting = "Everyone"
    AllowUserEdit = $false
    MappingConnectionName = "contoso.com"
    MappingPropertyName = "mail"
    MappingDirection = "Import"
}

**Comment by camiloborges** [comment]
I am on it

**Comment by camiloborges** [comment]
hey. what about order and grouping(can't remember how it is called in CA)?

**Comment by BrianFarnhill** [comment]
Good point - now sure how we include this. You got suggestions or ideas? Im pretty sure group is just another string property so that should be fine, but I forget about the ordering stuff.

**Comment by camiloborges** [comment]
Pretty sure I've got a script that adds the property, saves it, then retrieves all properties and reorder them. I am just a little worried that DSC might not like that as I think we could end up with another loop as property index might be changed by another property.
ie: there is a default property p26(A)  I add another one to p26(B). 
B is now p26, A is p27.
if I add C as p26 we have
C - p26
B - p27
A - p28.

I will code it up and we test in your super dupa sexy environment

**Comment by BrianFarnhill** [comment]
Yea I'm inclined to park the ordering to another day (maybe we do a separate resource to define the order of all properties so we avoid a loop like that)

**Comment by camiloborges** [comment]
could / should property order be another resource?

**Comment by camiloborges** [comment]
:)

**Comment by camiloborges** [comment]
check this out

param( $siteUrl)
Add-PSSnapin microsoft.sharepoint.powershell -ErrorAction SilentlyContinue
Add-Type -Path "C:\program files\common files\microsoft shared\web server extensions\15\isapi\Microsoft.Office.Server.dll"
 
 #$configFile =[xml] (Get-Content "./upsProperties.xml")
#function UPPReorder($configFile,$siteUrl){
 $config = [xml] (Get-Content "./upsProperties.xml")
 $mys = Get-SPSite $siteUrl
 $context = Get-SPServiceContext $mys
 $upcManager = New-Object Microsoft.Office.Server.UserProfiles.UserProfileConfigManager($context)
 
 #if you have several profile sub-types, you might want to change the following line and use the name of the desired profile sub-type
 $defaultUserProfileSubTypeName = [Microsoft.Office.Server.UserProfiles.ProfileSubtypeManager]::GetDefaultProfileName("User")
 $profileSubtypePropManager = $upcManager.ProfilePropertyManager.GetProfileSubtypeProperties($defaultUserProfileSubTypeName)
 
 foreach($property in $config.Configuration.Properties.childnodes){
 $propName = $property.Name
 Write-Host "Updating property $propName ..."
 $profileSubtypePropManager.SetDisplayOrderByPropertyName($property.Name,$property.Order)
 }
 $profileSubtypePropManager.CommitDisplayOrder()
 Write-Host "Finished."
#}
#SAMPLE USAGE
#UPPReorder C:\Temp\Blog\config.userproperties.xml http://spdevel.portal.com

**Comment by BrianFarnhill** [comment]
Lets call it now - yes, sort order of properties should be a separate resource - leave it out of this :)

**Comment by camiloborges** [comment]
hello.
please mark this as in progress :)

**Comment by BrianFarnhill** [comment]
All yours @camiloborges

**Comment by BrianFarnhill** [comment]
Released in v0.10 - closing this issue
