### ISSUE TITLE
Extend xSPWebApplication resource to include "general settings"

### ISSUE THREAD

**Issue by BrianFarnhill** [PowerShell/xSharePoint#41]
Extend the xSPWebAppliation resource top include the follow settings (seen in central admin under the "general settings" dialog)

 - TimeZone
 - Default Quota Template
 - Alerts (on/off and limit)
 - RSS
 - Blog API
 - Browser File Handling
 - Security Validation
 - Recycle bin settings
 - Maximum upload size
 - Customer experience program
 - Usage cookie

**Comment by camiloborges** [comment]
Hey. Check what I came up with.  This should allow addressing all the Web Application related items.

[ClassVersion("1.0.0")]
Class MSFT_xSPFilesTypes
{
    [write]String EnsureBlocked[];
    [write]String EnsureAllowed[];
};

[ClassVersion("1.0.0")]
Class MSFT_xSPOutgoingEmailSettings
{
    [Write] string SMTPServer;
    [Write] string FromAddress;
    [Write] string ReplyToAddress;
    [Write] string CharacterSet;
};

[ClassVersion("1.0.0")]
Class MSFT_xSPWebApplicationThrottling
{
    [write]String ListViewThreshold;
    [write]String AllowObjectModelOverride;
    [write]String AdminThreshold;
    [write]String ListViewLookupThreshold;
    [write]String HappyHour;
    [write]String UniquePermissionThreshold;
	[write]String RequestThrottling;
	[write]String ChangeLog;
};

[ClassVersion("1.0.0")]
Class MSFT_xSPWebApplicationExtension
{
    [write]String ApplicationPool;
    [write]String AllowAnonymous;
    [write]String AuthenticationMethod;
    [write]String HostHeader;
    [write]String Port;
	[write]String SSL;
	[write]String Zone;
};

[ClassVersion("1.0.0")]
Class MSFT_xSPWebApplicationWorkflowSettings
{
    [write]String ExternalWorkflowParticipantsEnabled;
    [write]String UserDefinedWorkflowsEnabled;
    [write]String EmailToNoPermissionWorkflowParticipantsEnable;
};

[ClassVersion("1.0.0")]
Class MSFT_xSPWebApplicationSettings
{
    [write]String TimeZone;
    [write]String UserDefinedWorkflowsEnabled;
    [write]String EmailToNoPermissionWorkflowParticipantsEnable;
    [write]String DefaultQuotaTemplate;
    [write]String Alerts;
    [write]String AlertsLimit;
    [write]String RSS;
    [write]String BlogAPI;
    [write]String BrowserFileHandling;
    [write]String SecurityValidation;
    [write]String RecycleBin;
    [write]String MaximumUploadSize;
    [write]String CustomerExperienceProgram;
    [write]String Usage ;
};

[ClassVersion("1.0.0.0"), FriendlyName("xSPWebApplication")]
class MSFT_xSPWebApplication : OMI_BaseResource
{
    [Key] string Name;
    [Required] string ApplicationPool;
    [Required] string ApplicationPoolAccount;
    [Required] string Url;
    [Write] boolean AllowAnonymous;
    [Write, ValueMap{"NTLM","Kerberos"}, Values{"NTLM","Kerberos"}] string AuthenticationMethod;
    [Write] string DatabaseName;
    [Write] string DatabaseServer;
    [Write] string HostHeader;
    [Write] string Path;
    [Write] string Port;
    [Write, EmbeddedInstance("MSFT_Credential")] String InstallAccount;
    [Write, EmbeddedInstance("MSFT_xSPWebApplicationSettings")] String GeneralSettings;
    [Write, EmbeddedInstance("MSFT_xSPWebApplicationWorkflowSettings")] String WorkflowSettings;
    [Write, EmbeddedInstance("MSFT_xSPWebApplicationExtension")] String Extensions;
    [Write, EmbeddedInstance("MSFT_xSPWebApplicationThrottling")] String Throttling;
    [Write, EmbeddedInstance("MSFT_xSPOutgoingEmailSettings")] String OutgoingEmailSettings;
    [Write, EmbeddedInstance("MSFT_xSPBlockedFilesTypes")] String FileTypes;
};

**Comment by camiloborges** [comment]
(please don't be too concerned with the data types as I didn't really  paid attention to them. idea was to show the concept

**Comment by BrianFarnhill** [comment]
This is part of PR #96 and will be closed when this is merged to dev

**Comment by BrianFarnhill** [comment]
This has been merged to dev in PR #96 and will be released in v0.8 - closing this issue
