### ISSUE TITLE
Extend xSPWebApplication resource to include "workflow settings"

### ISSUE THREAD

**Issue by BrianFarnhill** [PowerShell/xSharePoint#43]
Extend the xSPWebAppliation resource top include the follow settings (seen in central admin under the "workflow settings" dialog)

 - Enable user defined workflows
 - Allow internal users with no site access to get tasks
 - Allow external users to get tasks with a copy of the document

**Comment by camiloborges** [comment]
hello. which ones? 
I think you are referring to the following properties.

Allow internal users with no site access to get tasks
     EmailToNoPermissionWorkflowParticipantsEnabled


Allow external users to get tasks with a copy of the document
     ExternalWorkflowParticipantsEnabled
     

Enable user defined workflows:
    UserDefinedWorkflowsEnabled 

What about these ones?
     AllowDesigner
     AllowCreateDeclarativeWorkflow 
     AllowSaveDeclarativeWorkflowAsTemplate
     AllowSavePublishDeclarativeWorkflow 

I am not sure though.

**Comment by BrianFarnhill** [comment]
The initial ask was to mimic the settings on the workflow settings screen in central admin (when you select a web app then choose workflow settings from that drop down item in the ribbon), but happy to discuss others that aren't on there if you think they are relevant.

**Comment by BrianFarnhill** [comment]
This is part of PR #96 and will be closed when this is merged to dev

**Comment by BrianFarnhill** [comment]
This has been merged to dev in PR #96 and will be released in v0.8 - closing this issue
