### ISSUE TITLE
Add xSPAppUrls resource

### ISSUE THREAD

**Issue by BrianFarnhill** [PowerShell/xSharePoint#47]
The xSPAppUrls resource will be used to set the app urls that will be used for the farm. It should be structured as follows:

xSPAppUrls AppUrls
{
    AppDomain = "contosointranetapps.com"
    AppPrefix = "app"
}

**Comment by BrianFarnhill** [comment]
@camiloborges Did you say you were doing the app URLs with the app management service app?

**Comment by camiloborges** [comment]
Yes

**Comment by BrianFarnhill** [comment]
Cool, ill take the help wanting off this one then

**Comment by camiloborges** [comment]
updating mof schema . updating from AppUrls to AppDomain
class MSFT_xSPAppDomain : OMI_BaseResource
{
    [Key] string AppDomain;
    [Required] string Prefix;
    [Write, EmbeddedInstance("MSFT_Credential")] String InstallAccount;
    
};

**Comment by camiloborges** [comment]
@BrianFarnhill , please confirm you are ok with new name

**Comment by BrianFarnhill** [comment]
Fine with it dude

**Comment by BrianFarnhill** [comment]
This was merged to dev in PR #133 - closing this issue
