### ISSUE TITLE
Add xSPOutgoingEmailSettings resource

### ISSUE THREAD

**Issue by BrianFarnhill** [PowerShell/xSharePoint#48]
The xSPOutgoingEmailSettings  is responsible for setting outgoing email settings to either the whole form, or a specific web application. It should be structured as below:

xSPOutgoingEmailSettings MainWebAppOutgoingEmailSettings
{
    WebAppUrl = "https://sharepoint.contoso.com"
    SMTPServer = "mail.contoso.com"
    FromAddress = "noreply@sharepoint.contoso.com""
    ReplyToAddress = "noreply@sharepoint.contoso.com"
    CharacterSet = "65001"
}

The WebAppUrl parameter should be optional here. Where it is not present the settings should be applied to the farm. Where it is specified, they should be applied to the specific web application instead.

**Comment by camiloborges** [comment]
can I take this one too?

**Comment by BrianFarnhill** [comment]
All yours amigo

**Comment by BrianFarnhill** [comment]
This was merged in to dev in PR #96
