### ISSUE TITLE
Add xSPHealthAnalyzerRuleState resource

### ISSUE THREAD

**Issue by BrianFarnhill** [PowerShell/xSharePoint#49]
The xSPHealthAnalyzerRuleState resource will be used to set the status of a specific health analyser rule for the farm in the central administration site (to ensure that a specific rule is either enabled/disabled and if it is set to fix automaticaly or not). It will be represented as below:

xSPHealthAnalyzerRuleState DisableDiskSpaceRule
{
    Name = "Drives are at risk of running out of free space."
    Ensure = "Absent"
    InstallAcount = $InstallAccount
}

xSPHealthAnalyzerRuleState CompressDBsRule
{
    Name = "Database has large amounts of unused space."
    Ensure = "Present"
    FixAutomatically = $true
    InstallAcount = $InstallAccount
}

**Comment by ykuijs** [comment]
I am on it!
