### ISSUE TITLE
Nested Modules isn't loading (for some reason

### ISSUE THREAD

**Issue by mrpullen** [PowerShell/xSharePoint#53]
Attempting to run xManagedPath Resource, receiving the error 

The term 'Get-xSharePointAuthenticatedPSSession' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
    + CategoryInfo          : ObjectNotFound: (Get-xSharePointAuthenticatedPSSession:) [], CimException
    + FullyQualifiedErrorId : CommandNotFoundException
    + PSComputerName        : localhost

**Comment by mrpullen** [comment]
Configuration SPFarm {
   param([PSCredential]$InstallAccount)
   Import-DSCResource -ModuleName xSharePoint
   Node localhost {
      
        xSPManagedPath team {
              WebAppUrl = "http://sp2013"
              InstallAccount = $InstallAccount
              RelativeUrl = "team"
              Explicit = $false
              HostHeader = $false
        }
   }
}

**Comment by mrpullen** [comment]
xsharePoint.psd1 contains

NestedModules = @("modules\xSharePoint.DistributedCache\xSharePoint.DistributedCache.psm1",
                  "modules\xSharePoint.Util\xSharePoint.Util.psm1")

which looks right to me..

**Comment by NikCharlebois** [comment]
Shouldn't it be:

NestedModules = @("DSCResources\xSharePoint.DistributedCache\xSharePoint.DistributedCache.psm1",
 "modules\xSharePoint.Util\xSharePoint.Util.psm1")

Note the DSCResources folder for Distributed cache instead of the modules folder.

**Comment by NikCharlebois** [comment]
Can you try the following:

1 - Open xSharePoint.psd1;;
2 - Replace the line:
                                 CmdletsToExport = '*'
by
                                 CmdletssToExport = 'Get-xSharePointAuthenticatedPSSession'

and try again?

**Comment by mrpullen** [comment]
that worked, but now I am getting Remove-xSharePointNullParamValues is not recognized. I will just list all the commandlets in those modules.. 

Tx.

**Comment by NikCharlebois** [comment]
This seems to be a recurring problem in many DSC resources. I will try following up with the PowerShell team to get their input on this. In the meantime I might try to submit a pull request to ensure it works, listing all Cmdlets individually

Sent from my BlackBerry 10 smartphone on the Rogers network.
From: Michael Rees Pullen
Sent: Thursday, July 16, 2015 10:37 AM
To: PowerShell/xSharePoint
Reply To: PowerShell/xSharePoint
Cc: Charlebois-Laprade, Nikolas
Subject: Re: [xSharePoint] Nested Modules isn't loading (for some reason (#53)



that worked, but now I am getting Remove-xSharePointNullParamValues is not recognized. I will just list all the commandlets in those modules..

Tx.

�
