### ISSUE TITLE
Get-DSCConfiguration or Test-DSCConfiguration fail due to Get-TargetResource Hashtable return values.

### ISSUE THREAD

**Issue by mrpullen** [PowerShell/xSharePoint#56]
so setting a managed path using the xSharePoint module. When I run Test-DSCConfiguration or Get-DSCConfiguration the command fails ... error output below

C:\windows\system32\WindowsPowerShell\v1.0\Modules\xSharePoint\DscResources\MSFT_xSPManagedPath returned results that
are not valid from Get-TargetResource. The PathType key is not a valid property in the corresponding provider schema
file. The results from Get-TargetResource must be in a Hashtable format. The keys in the Hashtable must be the same as
the properties in the corresponding provider schema file.
At line:1 char:1
+ Get-DscConfiguration
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidResult: (MSFT_DSCLocalConfigurationManager:root/Microsoft/...gurationManager) [Ge
   t-DscConfiguration], CimException
    + FullyQualifiedErrorId : GetOperationResultInvalidResultFormat,Get-DscConfiguration

Looks like the return params from Get-TargetResource need to be very specific...

**Comment by BrianFarnhill** [comment]
Thanks for the report - we'll look in to resolving this, I suspect there are a couple of resources that don't conform to this approach so will look to bring them all in line at the same time.

**Comment by yeahnahyeah** [comment]
I get similar Hashtable format errors using other classes also. 

e.g.  

ErrorMessage is The PowerShell provider C:\Program Files\WindowsPowerShell\Modules\xSharePoint\DscResources\MSFT_xSPCreateFarm returned results that are not valid from Get-TargetResource. The FarmName key is not a valid property in the corresponding provider schema file. The results from Get-TargetResource must be in a Hashtable format. The keys in the Hashtable must be the same as the properties in the corresponding provider schema file.

The result is that Test-DscConfiguration always returns "false".

**Comment by BrianFarnhill** [comment]
Yea it's a known problem that is near the top of my todo list to rectify. I'll post here as soon as I have a fix published.

**Comment by yeahnahyeah** [comment]
Thanks Brian. Appreciate your efforts.

**Comment by BrianFarnhill** [comment]
Tagging as in progress as I'm now working on this one

**Comment by BrianFarnhill** [comment]
Hey guys, I have fixes for this in pull request #80 which is now pending code review. I've run Test-DSCConfiguration against a server with the configuration applied and I can now see a True value come out of it too. I'll advise here and close the issue when this hits the dev branch

**Comment by BrianFarnhill** [comment]
The fixes for this are now included in the dev branch, I'm closing off this issue. Thanks for reporting it guys
