### ISSUE TITLE
Random 'S' below class MSFT_xSPCreateFarm - ModuleVersion = '0.3.1.0'

### ISSUE THREAD

**Issue by yeahnahyeah** [PowerShell/xSharePoint#66]
Random 'S' below class MSFT_xSPCreateFarm in module MSFT_xSPCreateFarm causes the class to not work.

ModuleVersion = '0.3.1.0'

**Comment by BrianFarnhill** [comment]
Looking at the current scripts for version 0.4.0.0 I don't see the S you're talking about, so I believe this has already been checked in and sorted. Can you have a look at the current version from the PS gallery or from the releases here on GitHub and let me know if you believe it has been resolved as well?

**Comment by yeahnahyeah** [comment]
Sorry Brian, I think I downloaded from the wrong place. When downloading the ZIp from here https://github.com/PowerShell/xSharePoint just now (ModuleVersion = '0.4.0.0') the 'S' is there (xSharePoint-dev.zip). 

When I downloaded from the releases page: https://github.com/PowerShell/xSharePoint/releases the 'S' is not there (xSharePoint.zip).

**Comment by BrianFarnhill** [comment]
All good, I see it in the dev branch now - I'll make sure its caught before we push a new release out to the main branch. Thanks for reporting the issue!

**Comment by BrianFarnhill** [comment]
This has been corrected in the dev branch now by pull request #67 - closing this issue off
