### ISSUE TITLE
xSPInstallPrereqs calls Get-xSharePointAssemblyVerion

### ISSUE THREAD

**Issue by heidi2** [PowerShell/xSharePoint#75]
Since the prerequisites need to be installed before the assembly, this will never actually install the prereqs.

**Comment by BrianFarnhill** [comment]
Hi Heidi,

The xSPInstallPrereqs uses Get-xSharePointAssemblyVersion to get the version number from prerequisiteinstaller.exe (from the InstallerPath property). This gives us the version number of the prerequisite installer, which lines up with the version number of SharePoint we are dealing with as well, meaning we can use that to determine which prerequisite installations to check for. From our own testing it works fine for both versions - have you seen this not work correctly somewhere though? Would be keen to know what scenarios it doesn't work in so we can accommodate them. 

 - B

**Comment by heidi2** [comment]
Ah, OK, I think the actual problem may be that I'm running powershell version 4.The *version* property that's used in Get-xSharePointAssemblyVersion appears to have been [introduced in v5](https://msdn.microsoft.com/en-us/library/system.management.automation.applicationinfo_members%28v=vs.85%29.aspx). Are you still intending to support v4 at this stage, or do I just need to upgrade?

**Comment by BrianFarnhill** [comment]
We are absolutely looking to support PowerShell 4 as well - let me spin up an environment where I can validate that and I'll let you know how I go. What we do though should have been working fine though but I'll confirm. Do you have a specific error message or logs or anything you can share with me about your error that you can share with me?

**Comment by BrianFarnhill** [comment]
OK it would appear you are correct Heidi - I can see how we address this as well, I'll work on getting a fix pushed in for this one and post here when it is resolved.

**Comment by BrianFarnhill** [comment]
Hey Heidi,

I have a fix that appears to be working in my repo - I'll do some integration and functional tests with it to make sure it behaves correctly in a few scenarios and then I'll post the fix. Expect it within a few days to a week, and I'll post here and close this issue when it's done.

Thanks for reporting the bug!

**Comment by heidi2** [comment]
Excellent! Thanks for the quick response, and all the work you've put into this project.I'm just getting started with DSC, and it's great being able to do so much.

**Comment by BrianFarnhill** [comment]
Hi @heidi2 - the fix for this issue is included in pull request #78 - I'm just waiting on a code review before I move this in to the dev branch though. In the mean time if you want to apply the fix to your own scripts the change is in xSharePoint.Util.psm1, in the Get-xSharePointAssemblyVersion function, the one line it uses should be:

    return (Get-Command $PathToAssembly).FileVersionInfo.FileMajorPart

This will work in PS4 and PS5, so should resolve the issue you are seeing while we get the rest of the changes in that pull request reviewed and moved in. I'll keep this issue open until the fix is officially part of the dev branch though.

**Comment by BrianFarnhill** [comment]
This fix is now merged in to the dev branch and will be in the next release - closing this issue
