### ISSUE TITLE
Add xSPWebAppBlockedFileTypes resource

### ISSUE THREAD

**Issue by BrianFarnhill** [PowerShell/xSharePoint#89]
We are looking to add a resource to manage the blocked file types that are used on a web application. The syntax would look like this:

    xSPWebAppBlockedFileTypes BlockFileTypes
    {
        WebAppName = "SharePoint sites"
        BlockedFileTypes = "exe,dll"
        AllowedFileTypes = "config,json"
    }

The concept here is that an administrator can specify a list of file types to ensure are in the blocked file types list for the given web application, but also to specify file types that are to never be in the list (so in the case of them being manually added they can be removed).

**Comment by camiloborges** [comment]
Hello. Just trying to keep things consistent... xSPOutgoingEmailSettings takes WebAppUrl as parameter. This one asks for WebAppName.
Should we have only one way of referring to the web app?

**Comment by BrianFarnhill** [comment]
Nice catch, it should use the URL not the name

**Comment by BrianFarnhill** [comment]
Also I'm considering moving this one to be a property on the existing xSPWebApplication object rather than an individual resource, let me know if you are going to work on this one first.

**Comment by kilasuit** [comment]
I would suggest that this should be as part of the xSPWebApplication resource rather than an individual resource

**Comment by kilasuit** [comment]
To expand on that setting that are able to be applied at the WebApplication level I would be more inclined to group them under the xSPWebApplication resource

**Comment by camiloborges** [comment]
I was half way through it already :P but happy to change.
it makes sense to be just an enhancement for the xSPWebApplication indeed. I just shut the VMs down, will look into it tomorrow

**Comment by BrianFarnhill** [comment]
Agreed - Camilio ping me and we can have a chat about how to move it to the webapp object. I'll also mark this as in progress with you as well :)

**Comment by BrianFarnhill** [comment]
This has been merged to dev in PR #96 and will be released in v0.8 - closing this issue
