### ISSUE TITLE
Add xSPQuotaTemplate resource

### ISSUE THREAD

**Issue by ykuijs** [PowerShell/xSharePoint#91]
The xSPQuotaTemplate resource will be used to add or remove a quota template. It will be represented as below:

xSPQuotaTemplate NewQuotaTemplate
{
Name= "1GB"
StorageMaxInMB=1024
StorageWarningInMB=512
MaximumUsagePointsSolutions=300
WarningUsagePointsSolutions=200
Ensure=”Present”
}

**Comment by ykuijs** [comment]
I am on it!

**Comment by BrianFarnhill** [comment]
Closing this one as it has been merged
