### ISSUE TITLE
Add xSPTimerJobState resource

### ISSUE THREAD

**Issue by ykuijs** [PowerShell/xSharePoint#92]
The xSPTimerJobState resource will be used to configure a timer job and make sure it is in a specific state. It will be represented as below:

xSPTimerJobState DisableTimerJob
{
Name = "Dead Site Delete"
WebApplication = "SharePoint - www.domain.com80"
Enabled = $true
Schedule="weekly at sat 5:00"
}

**Comment by ykuijs** [comment]
@BrianFarnhill - I am on it!

**Comment by BrianFarnhill** [comment]
All yours @ykuijs

**Comment by BrianFarnhill** [comment]
This is now merged to dev, closing this issue
