### ISSUE TITLE
Add xSPAntivirusSettings resource

### ISSUE THREAD

**Issue by ykuijs** [PowerShell/xSharePoint#93]
The xSPAntivirusSettings resource will be used to configure the anti virus farm settings. It will be represented as below:

xSPAntivirusSettings ConfigureAV
{
ScanDocumentsOnUpload=$false
ScanDocumentsOnDownload=$false
AllowUsersToDownloadInfectedDocuments=$true
AttemptToCleanInfectedDocuments=$false
TimeoutDuration=300
NumberOfThreads=5
}

**Comment by ykuijs** [comment]
Working on it!

**Comment by BrianFarnhill** [comment]
Merged in to dev, closing this issue
