### ISSUE TITLE
Add xSPPasswordChangeSettings resource

### ISSUE THREAD

**Issue by ykuijs** [PowerShell/xSharePoint#94]
The xSPPasswordChangeSettingsresource will be used to configure the farm wide Pasword Change settings. It will be represented as below:

xSPPasswordChangeSettings ConfigurePasswordChange
{
MailAddress=”test@domain.com”
DaysBeforeExpiry=10
PasswordChangeWaitTimeSeconds=45
NumberOfRetries=5
}

**Comment by camiloborges** [comment]
I am on it :)

**Comment by BrianFarnhill** [comment]
Let me know if you need any help buddy

**Comment by BrianFarnhill** [comment]
This is part of PR #96 and will be closed off once this is merged to dev

**Comment by BrianFarnhill** [comment]
This has been merged to dev in PR #96 and will be released in v0.8 - closing this issue
