### ISSUE TITLE
Add xSPFarmAdministrators resource

### ISSUE THREAD

**Issue by ykuijs** [PowerShell/xSharePoint#99]
The xSPFarmAdministrators resource will be used to manage the members of the Farm Administrators group. It will be represented as below:

xSPFarmAdministrators FarmAdmins
{
 Members=”DOMAIN\UserX”, "BUILTIN\Administrators", "DOMAIN\sp_farm"
 MembersToInclude=""DOMAIN\User1"
 MembersToExclude="DOMAIN\User2"
}

The Members property is used to enforce a specific list of users which have to be a member of the Farm Administrators group and cannot be used together with the MembersToInclude and/or MembersToExclude properties.
The MembersToInclude and MembersToExclude properties are used to make sure one (or a set of) user is added to Farm Admins (MembersToInclude) or a user can never be a member of the Farm Admins (MembersToExclude).

**Comment by ykuijs** [comment]
I have created this resource already, which is included in PR 98

**Comment by BrianFarnhill** [comment]
#98 Has been merged in to dev, closing this issue
